# This is a basic workflow to help you get started with GitHub Actions

name: Getting Started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-on-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: sh ./github-actions-script.sh

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Nothing to see in multi-line script
      #     echo Here is what is in the folder
      #     ls -a
      - name: Step 1 - Log the pre-build disc space
        run: ls

      - name: Step 2 - Checkout the main Github branch
        uses: actions/checkout@v3

      - name: Step 3 - Setup JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Step 4 - Build your Jakarta Web App using Maven
        run: echo mvn -B package --file pom.xml

      - name: Step 5 Check windows execution policy
        run: |
          echo Here is the Windows execution policy:
          Get-ExecutionPolicy

      - name: Step 6 - List Windows environment variables
        run: env

  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Log he pre-build disc space
        run: df

      - name: Step 2 - Checkout the main Github branch
        uses: actions/checkout@v3

      - name: Step 3 - Setup JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Step 4 - Build your Jakarta Web App using Maven
        run: echo mvn -B package --file pom.xml

      - name: Step 5 Build the native Android App
        run: |
          echo Here is the ANDROID_SDK_ROOT
          echo $ANDROID_SDK_ROOT

      - name: Step 6 - Run your Selenium tests
        run: |
          echo the SELENIUM_JAR_PATH
          echo $SELENIUM_JAR_PATH

      - name: Step 7 - Logbuild tool versions
        run: |
          git --version
          mvn --version
          ant -version
          gradle --version

      - name: Step 8 - Log the post-build disc space
        run: df
        
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Step - 1 - Echo out a GitHub Actions secret to the logs
        run: |
          echo "The GitHub Actions Secret will be masked: "
          echo ${{ secrets.GITHUB_TOKEN }}
          echo "Trick to echo GitHub Actions Secret: "
          echo ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'

      - name: Triggering GitHub workflow
        run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" https://api.github.com/repos/srinikhiltumu1/getting-started-github-actions/actions/workflows/actions-artifact-example.yml/dispatches -d '{"ref":"main"}'